### ISSUE TITLE
Example is not working on production

### ISSUE THREAD

**Issue by 0x0badc0de** [ciena-blueplanet/ember-pollboy#19]
Hi, example provided in readme works just fine in development but fails for me on production because `this.get('usersPoller')` in `afterModel` returns the poller created on previous route visit, this poller has `isStopped: true`. I've made a quick fix by explicitly setting poller to null in `deactivate`, i.e.:

```
  deactivate () {
    const usersPoller = this.get('usersPoller')
    this.get('pollboy').remove(usersPoller)
    this.set('usersPoller', null)
  }
```

but wonder if this is something wrong w/ my set up and some another fix should be applied.
Could you suggest?

**Comment by LachlanRidley** [comment]
I had this same issue crop up with the example code provided in the readme. Unless I missed something there's definitely a step missing. I ended up using the same solution as @0x0badc0de.

**Comment by 0x0badc0de** [comment]
For those who interested I've ended up w/ switching to `ember-concurrency` w/ slightly different logic - poll every `pollInterval` unless document is hidden. I.e. don't instantly re-poll once document became visible:
```
import Ember from 'ember';
import { task, timeout } from 'ember-concurrency';

const pollInterval = 60000;

export default Ember.Route.extend({
  model() {
    return this.store.findAll('node');
  },

  setupController() {
    this._super(...arguments);
    this.get('pollServerForChanges').perform();
  },

  pollServerForChanges: task(function * () {
    while (true) {
      yield timeout(pollInterval);
      if (!document.hidden) {
        yield this.model();
      }
    }
  }).cancelOn('deactivate').restartable()
});
```

UPD: or similar to pollboy:
```
import Ember from 'ember';
import { task, timeout, waitForEvent } from 'ember-concurrency';

const pollInterval = 60000;

export default Ember.Route.extend({
  model() {
    return this.store.findAll('node');
  },

  setupController() {
    this._super(...arguments);
    this.get('pollServerForChanges').perform();
  },

  pollServerForChanges: task(function * () {
    while (true) {
      yield timeout(pollInterval);
      if (document.hidden) {
        yield waitForEvent(Ember.$(document), 'visibilitychange');
      }
      yield this.model();
    }
  }).cancelOn('deactivate').restartable()
});
```
